apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-skvb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-skvb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-skvb
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-skvb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-skvb
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-xwoz-tenant/rhtap-demo-app/hacbs-test-project-skvb@sha256:ddebdc49b2ca1e31ebf1f10009561dd56c723fd3e228fece7953869caada025f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
